# Generated by Django 5.1.3 on 2024-11-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('utilise', models.BooleanField()),
                ('numero_ordre_alphabetique', models.IntegerField()),
                ('unique_id', models.UUIDField(default=5, editable=False, unique=True)),
            ],
        ),
    ]
