# Generated by Django 5.1.3 on 2024-11-13 14:34

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('utilise', models.BooleanField()),
                ('numero_ordre_alphabetique', models.IntegerField()),
                ('boite', models.IntegerField(default=backend.models.generate_unique_id, editable=False, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Eleves',
        ),
    ]
