# Generated by Django 5.1.3 on 2024-12-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_eleve_delete_eleves"),
    ]

    operations = [
        migrations.AddField(
            model_name="eleve",
            name="groupe_AP",
            field=models.CharField(
                choices=[("MA", "Groupe 1: Mardi"), ("JE", "Groupe 2: Jeudi")],
                default=0,
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
